version: "3.8"

services:
  db:
    image: postgres:16
    container_name: drag-race-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: drag_race_db
    ports:
      - "5432:5432"
    volumes:
      - drag_race_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  drag_race_db_data:
