spring.application.name=drag_race
spring.datasource.url=jdbc:postgresql://localhost:5432/drag_race_db
spring.datasource.username=admin
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update